### ISSUE TITLE
image memory cache not working

### ISSUE THREAD

**Issue by usamashafiqs** [prongbang/cached_memory_image#1]
## When i use CachedMemoryImageProvider this error occurred

<img width="800" src="https://user-images.githubusercontent.com/18592683/176643209-f3909c6a-9947-4f8d-8c4a-ddf702527578.png" />

## When i use isExists it show image is cached.

<img width="800" src="https://user-images.githubusercontent.com/18592683/176642618-bf7b0375-eb71-43bf-9bb9-c61d65056752.png" />

## Output
<img width="900" src="https://user-images.githubusercontent.com/18592683/176641808-0288497c-e696-4ac6-8161-458bc950ebe5.png" />

**Comment by mcfriend99** [comment]
Did it ever work?

**Comment by prongbang** [comment]
"Thank you for reporting the issue. You can address it by using version cached_memory_image: ^1.5.0 and updating your code as follows in Dart:

```dart
CachedMemoryImageProvider(
   key,
   cached: CachedImage.readOnly,
)
```
